fixes
interledgerjs/ilp-plugin-payment pull request #1
Opened 2018-06-04 18:06 UTC by rhuairahrighairidh

A collection of small fixes for
 - typos
 - calling missing keys on objects
 - missing imports

2018-06-13 21:28 UTC, sharafian requested changes
Thanks! This look really good but there's a couple of small issues

2018-06-13 21:28 UTC, sharafian commented on src/client.js
>          custom: {
rather than changing all the rest of the code to use the `custom` subprotocol, this line should be changed to use `protocolMap`.

2018-06-13 21:28 UTC, sharafian commented on src/server.js
> +      this._moneyHandler(String(value))
A server plugin shouldn't call the money handler when money is received from a client, because it does all balance logic internally. Instead, the connector should be configured to not use balance logic for the server plugin.

2018-07-20 16:44 UTC, rhuairahrighairidh commented
Hey @sharafian, I implemented the changes you requested.
Also updated it to the latest btp and mini-account plugins.

2018-07-20 17:35 UTC, sharafian approved these changes

2019-06-06 16:49 UTC, merged